EIDD.duplicationDescList = {
    [001] = "Additional copies have the same effect",
    [002] = "Adds an additional tear with no further decrease in fire rate#This can be stacked up to 16 tears",
    [003] = "No additional effect",
    [004] = "No additional damage multiplier",
    [005] = "No additional range multiplier or range",
    [006] = "Only tears up",
    [007] = "Damage up does not stack",
    [008] = "Gives an additional familiar",
    [009] = "No additional effect",
    [010] = "Maximum of 3 orbitals",
    [011] = "Gives another life",
    [012] = "No additional damage multiplier",
    [013] = "Stat changes stack",
    [014] = "Only increases range",
    [015] = "Additional copies have the same effect",
    [016] = "Additional copies have the same effect",
    [017] = "Additional copies have the same effect",
    [018] = "Additional copies have the same effect",
    [019] = "Additional copies have the same effect",
    [020] = "No additional effect",
    [021] = "No additional effect",
    [022] = "Additional copies have the same effect",
    [023] = "Additional copies have the same effect",
    [024] = "Additional copies have the same effect",
    [025] = "Additional copies have the same effect",
    [026] = "Additional copies have the same effect",
    [027] = "Additional copies have the same effect",
    [028] = "Additional copies have the same effect",
    [029] = "Additional copies have the same effect",
    [030] = "No additional contact damage",
    [031] = "Additional copies have the same effect",
    [032] = "Additional copies have the same effect",
    [033] = "", --active
    [034] = "", --active
    [035] = "", --active
    [036] = "", --active
    [037] = "", --active
    [038] = "", --active
    [039] = "", --active
    [040] = "", --active
    [041] = "", --active
    [042] = "", --active
    [043] = nil, --NON EXISTANT
    [044] = "", --active
    [045] = "", --active
    [046] = "Only luck up",
    [047] = "", --active
    [048] = "No additional effect",
    [049] = "", --active
    [050] = "Additional copies have the same effect",
    [051] = "Increases additional deal chance to 15% with two or more",
    [052] = "Fire one additional bomb in a side by side spread up to a maximum of 16 bombs",
    [053] = "No additional effect",
    [054] = "No additional effect",
    [055] = "No additional effect",
    [056] = "", --active
    [057] = "Give another familiar",
    [058] = "", --active
    [059] = nil, --NON EXISTANT
    [060] = "No additional effect",
    [061] = nil, --NON EXISTANT
    [062] = "No additional healing effect",
    [063] = "No additional effect",
    [064] = "Price is lowered to {{ColorSilver}}price / (n + 1){{CR}}, where {{ColorSilver}}n{{CR}} is the number of {{ColorObjName}}Steam Sales{{CR}}",
    [065] = "", --active
    [066] = "", --active
    [067] = "Gives an additional familiar",
    [068] = "Adds an additional laser for every extra copy of the item up to a maximum of 16, with no downgrade to damage or tears",
    [069] = "No additional effect",
    [070] = "Additional copies have the same effect",
    [071] = "Additional copies have the same effect",
    [072] = "Additional copies have the same effect",
    [073] = "", --CUBE
    [074] = "Additional copies have the same effect",
    [075] = "Spawn a pill and restore 2 hearts",
    [076] = "No additional effect",
    [077] = "", --active
    [078] = "", --active
    [079] = "Additional copies have the same effect",
    [080] = "Additional copies have the same effect",
    [081] = "Gives 9 additional lives",
    [082] = "Only speed up",
    [083] = "", --active
    [084] = "", --active
    [085] = "", --active
    [086] = "", --active
    [087] = "No additional effect",
    [088] = "Gives an additional familiar",
    [089] = "No additional effect",
    [090] = "Only tears up and speed down",
    [091] = "No additional effect",
    [092] = "Additional copies have the same effect",
    [093] = "", --active
    [094] = "Gives an additional familiar",
    [095] = "Gives an additional familiar",
    [096] = "Gives an additional familiar",
    [097] = "", --active
    [098] = "Gives an additional familiar",
    [099] = "Gives an additional familiar",
    [100] = "Gives an additional familiar",
    [101] = "Additional copies have the same effect",
    [102] = "", --active
    [103] = "No additional effect",
    [104] = "No additional effect",
    [105] = "", --active
    [106] = "No additional effect",
    [107] = "", --active
    [108] = "No additional effect",
    [109] = "Damage up does not stack, no additional effect",
    [110] = "Only range up",
    [111] = "", --active
    [112] = "Gives an additional familiar",
    [113] = "Gives an additional familiar",
    [114] = "Grants an extra knife that fires slightly diagonally from the original#Picking up more than 16 knives won't fire more knives but will still modify the angle at which they're shot",
    [115] = "Only tears up",
    [116] = "No additional effect",
    [117] = "Only one {{ColorObjName}}Dead Bird{{CR}} will ever spawn",
    [118] = "1.2x damage multiplier, +1 damage, and doubles the beam's width#Further copies only grant +1 damage",
    [119] = "Additional copies have the same effect",
    [120] = "Only tears and speed up",
    [121] = "Additional copies have the same effect",
    [122] = "No additional effect",
    [123] = "", --active
    [124] = "", --active
    [125] = "Only +5 bombs",
    [126] = "", --active
    [127] = "", --active
    [128] = "Gives an additional familiar",
    [129] = "Additional copies have the same effect",
    [130] = "", --active
    [131] = "Gives an additional familiar",
    [132] = "No additional effect",
    [133] = "", --active
    [134] = "No additional effect",
    [135] = "", --active
    [136] = "", --active
    [137] = "", --active
    [138] = "Additional copies have the same effect",
    [139] = "Only spawn 1 random trinket, no additional effect",
    [140] = "Only +5 bombs",
    [141] = "Additional copies have the same effect",
    [142] = "No additional effect",
    [143] = "Additional copies have the same effect",
    [144] = "Gives an additional familiar",
    [145] = "", --active
    [146] = "", --active
    [147] = "", --active
    [148] = "No additional effect",
    [149] = "No additional effect",
    [150] = "No additional effect",
    [151] = "No additional effect",
    [152] = "No additional effect",
    [153] = "Adds +2 tears, up to the maximum of 16",
    [154] = "No additional effect",
    [155] = "Gives an additional familiar",
    [156] = "No additional effect",
    [157] = "No additional effect",
    [158] = "", --active
    [159] = "No additional effect",
    [160] = "", --active
    [161] = "Gives another respawn with the same effect",
    [162] = "No additional effect",
    [163] = "Gives an additional familiar",
    [164] = "", --active
    [165] = "Additional copies have the same effect",
    [166] = "", --active
    [167] = "Gives an additional familiar",
    [168] = "Fires a barrage of missiles for each copy, up to 16",
    [169] = "No additional effect",
    [170] = "Gives an additional familiar",
    [171] = "", --active
    [172] = "Gives an additional familiar",
    [173] = "No additional effect",
    [174] = "Gives an additional familiar",
    [175] = "", --active
    [176] = "Additional copies have the same effect",
    [177] = "", --active
    [178] = "Gives an additional familiar",
    [179] = "Only grants 1 eternal heart",
    [180] = "No additional effect",
    [181] = "", --active
    [182] = "Only HP up, tears down, and shot speed down",
    [183] = "Additional copies have the same effect",
    [184] = "Only HP up",
    [185] = "No additional effect",
    [186] = "", --active
    [187] = "Gives an additional familiar",
    [188] = "Gives an additional familiar",
    [189] = "Additional copies have the same effect",
    [190] = "Additional copies have the same effect",
    [191] = "No additional effect",
    [192] = "", --active
    [193] = "Additional copies have the same effect",
    [194] = "Planetarium chance does not stack",
    [195] = "Additional copies have the same effect",
    [196] = "Additional copies have the same effect",
    [197] = "Additional copies have the same effect",
    [198] = "Additional copies have the same effect",
    [199] = "No additional effect",
    [200] = "No additional effect",
    [201] = "Only damage up",
    [202] = "No additional effect",
    [203] = "No additional effect",
    [204] = "No additional effect",
    [205] = "No additional effect",
    [206] = "Adds another head and further increases tears and damage, but only fires tears from one head.",
    [207] = "", --BALL
    [208] = "Only damage up",
    [209] = "Only +5 bombs",
    [210] = "No additional effect",
    [211] = "No additional effect",
    [212] = "Each copy's activation is calculated separately, increased odds for one to revive Isaac",
    [213] = "Only shot speed down",
    [214] = "Only range up",
    [215] = "No additional effect",
    [216] = "Additional copies have the same effect",
    [217] = "No additional effect",
    [218] = "No additional effect",
    [219] = "Only HP up",
    [220] = "Only +5 bombs",
    [221] = "No additional effect",
    [222] = "Only tears up",
    [223] = "Only +5 bombs",
    [224] = "No additional effect",
    [225] = "No additional effect",
    [226] = "Additional copies have the same effect",
    [227] = "Only +3 coins",
    [228] = "Only tears up",
    [229] = "Adds 12 tears to the barrage",
    [230] = "No additional effect on fear tears, otherwise same effect",
    [231] = "No additional effect",
    [232] = "No additional effect",
    [233] = "No additional effect",
    [234] = "No additional effect",
    [235] = nil, --NON EXISTANT
    [236] = "No additional effect",
    [237] = "Only damage up and tears down",
    [238] = "Gives an additional familiar",
    [239] = "Gives an additional familiar",
    [240] = "Stat changes stack",
    [241] = "Increases the number of room drops by one and lowers the chance of getting nothing",
    [242] = "No additional effect",
    [243] = "No additional effect",
    [244] = "No additional effect",
    [245] = "Adds one tear without lowering damage",
    [246] = "No additional effect",
    [247] = "No additional effect",
    [248] = "No additional effect",
    [249] = "No additional effect",
    [250] = "No additional effect",
    [251] = "No additional effect",
    [252] = "No additional effect",
    [253] = "Additional copies have the same effect",
    [254] = "No additional effect",
    [255] = "Additional copies have the same effect",
    [256] = "Only +5 bombs",
    [257] = "No additional effect",
    [258] = "No additional effect",
    [259] = "Only damage up",
    [260] = "Only +1 Black Heart",
    [261] = "No additional effect",
    [262] = "Only +1 Black Heart",
    [263] = "", --active
    [264] = "Gives an additional familiar",
    [265] = "Gives an additional familiar",
    [266] = "Gives an additional familiar",
    [267] = "Gives an additional familiar",
    [268] = "Gives an additional familiar",
    [269] = "Gives an additional familiar",
    [270] = "Gives an additional familiar",
    [271] = "Gives an additional familiar",
    [272] = "Gives an additional familiar",
    [273] = "Gives an additional familiar",
    [274] = "Only one fly will ever appear",
    [275] = "Gives an additional familiar",
    [276] = "No additional effect",
    [277] = "Gives an additional familiar",
    [278] = "Gives an additional familiar",
    [279] = "Gives an additional familiar",
    [280] = "Gives an additional familiar",
    [281] = "Gives an additional familiar",
    [282] = "", --active
    [283] = "", --active
    [284] = "", --active
    [285] = "", --active
    [286] = "", --active
    [287] = "", --active
    [288] = "", --active
    [289] = "", --active
    [290] = "", --active
    [291] = "", --active
    [292] = "", --active
    [293] = "", --active
    [294] = "", --active
    [295] = "", --active
    [296] = "", --active
    [297] = "", --active
    [298] = "", --active
    [299] = "No additional effect",
    [300] = "No additional effect",
    [301] = "Only +3 Soul Hearts",
    [302] = "No additional effect",
    [303] = "No additional effect",
    [304] = "Only gives additional pickups",
    [305] = "No additional effect",
    [306] = "No additional effect",
    [307] = "Only gives additional pickups as well as tears, damage, and HP up ",
    [308] = "No additional effect",
    [309] = "Only tears up",
    [310] = "No additional effect",
    [311] = "Gives another respawn with the same effect",
    [312] = "Only HP up",
    [313] = "Extra shield for the room it is obtained, but is removed after leaving the room",
    [314] = "Only HP up",
    [315] = "No additional effect",
    [316] = "No additional effect",
    [317] = "No additional effect",
    [318] = "Gives an additional familiar",
    [319] = "Gives an additional familiar",
    [320] = "Gives an additional familiar",
    [321] = "Gives an additional familiar",
    [322] = "Gives an additional familiar",
    [323] = "", --active
    [324] = "", --active
    [325] = "", --active
    [326] = "", --active
    [327] = "No additional effect",
    [328] = "Only damage up",
    [329] = "An additional smaller tear will orbit the main tear#A maximum of 15 smaller tears can orbit the main tear",
    [330] = "No additional effect",
    [331] = "Stat changes stack",
    [332] = "Gives another respawn with the same effect",
    [333] = "No additional effect",
    [334] = "Additional copies have the same effect",
    [335] = "Only +2 Soul Hearts",
    [336] = "Only range down",
    [337] = "No additional effect",
    [338] = "", --active
    [339] = "Additional copies have the same effect",
    [340] = "Additional copies have the same effect",
    [341] = "Additional copies have the same effect",
    [342] = "Additional copies have the same effect",
    [343] = "Additional copies have the same effect",
    [344] = "Additional copies have the same effect",
    [345] = "Additional copies have the same effect",
    [346] = "Additional copies have the same effect",
    [347] = "", --active
    [348] = "", --active
    [349] = "", --active
    [350] = "No additional effect",
    [351] = "", --active
    [352] = "", --active
    [353] = "Only +5 bombs",
    [354] = "Additional copies have the same effect",
    [355] = "Additional copies have the same effect",
    [356] = "No additional effect",
    [357] = "", --active
    [358] = "Fire one extra tear, equally spaced between the two initial tears",
    [359] = "Only damage up",
    [360] = "Gives an additional familiar",
    [361] = "Gives an additional familiar",
    [362] = "Gives an additional familiar",
    [363] = "Gives an additional familiar",
    [364] = "Gives an additional familiar",
    [365] = "Multiple flies, but nearly always stacked together",
    [366] = "Only +5 bombs",
    [367] = "Only +5 bombs",
    [368] = "No additional effect",
    [369] = "Only range up",
    [370] = "Additional copies have the same effect",
    [371] = "No additional effect",
    [372] = "Gives an additional familiar",
    [373] = "No additional effect",
    [374] = "No additional effect",
    [375] = "No additional effect",
    [376] = "No additional effect",
    [377] = "No additional effect",
    [378] = "No additional effect",
    [379] = "No additional effect",
    [380] = "Only +5 coins",
    [381] = "Tears up and gives an additional item for the next run, up to 10 items",
    [382] = "", --active
    [383] = "", --active
    [384] = "Gives an additional familiar",
    [385] = "Gives an additional familiar",
    [386] = "", --active
    [387] = "Gives an additional familiar",
    [388] = "Gives an additional familiar",
    [389] = "Gives an additional familiar",
    [390] = "Gives an additional familiar",
    [391] = "No additional effect",
    [392] = "No additional effect",
    [393] = "No additional effect",
    [394] = "Stat changes stack",
    [395] = "Fires an additional laser ring#Maximum of 16 rings",
    [396] = "", --active
    [397] = "Stat changes stack",
    [398] = "No additional effect",
    [399] = "No additional effect",
    [400] = "No additional effect",
    [401] = "No additional effect",
    [402] = "Only addition pickups",
    [403] = "Gives an additional familiar, doesn't change health bars",
    [404] = "Gives an additional familiar",
    [405] = "Gives an additional familiar",
    [406] = "", --active
    [407] = "No additional effect",
    [408] = "No additional effect",
    [409] = "Only +2 Black Hearts",
    [410] = "No additional effect",
    [411] = "No additional effect",
    [412] = "Can get up to 8 familiars, but cannot get an already obtained familiar",
    [413] = "No additional effect",
    [414] = "No additional effect",
    [415] = "Only +2 Soul Hearts",
    [416] = "No additional effect",
    [417] = "Gives an additional familiar",
    [418] = "No additional effect",
    [419] = "", --active
    [420] = "No additional effect",
    [421] = "", --active
    [422] = "", --active
    [423] = "No additional effect",
    [424] = "No additional effect",
    [425] = "No additional effect",
    [426] = "Will follow the last obtained familiar that has the same movement pattern",
    [427] = "", --active
    [428] = "Additional copies have the same effect",
    [429] = "No additional effect",
    [430] = "Will follow the last obtained familiar that has the same movement pattern",
    [431] = "Will follow the last obtained familiar that has the same movement pattern",
    [432] = "Only +5 bombs",
    [433] = "Gives an additional familiar",
    [434] = "", --active
    [435] = "Gives an additional familiar",
    [436] = "Stat changes stack, Gives an additional familiar",
    [437] = "", --active
    [438] = "Additional copies have the same effect",
    [439] = "", --active
    [440] = "No additional effect",
    [441] = "", --active
    [442] = "No additional effect",
    [443] = "Only tears up",
    [444] = "No additional effect",
    [445] = "Stat changes stack",
    [446] = "No additional effect",
    [447] = "No additional effect",
    [448] = "No additional effect",
    [449] = "Only +1 Soul Heart",
    [450] = "No additional effect",
    [451] = "Only drops a card or rune",
    [452] = "No additional effect",
    [453] = "Only range up",
    [454] = "Only drops a random card, rune, or pill",
    [455] = "Additional copies have the same effect",
    [456] = "Additional copies have the same effect",
    [457] = "Only +1 Soul Heart",
    [458] = "Only drops a random trinket",
    [459] = "No additional effect",
    [460] = "No additional effect",
    [461] = "No additional effect",
    [462] = "No additional effect",
    [463] = "Only damage up",
    [464] = "Only +2 Soul Hearts",
    [465] = "Only tears up",
    [466] = "No additional effect",
    [467] = "Gives an additional familiar",
    [468] = "Will follow the last obtained familiar that has the same movement pattern",
    [469] = "Gives an additional familiar",
    [470] = "Gives an additional familiar",
    [471] = "Gives an additional familiar",
    [472] = "Familiars follow the last {{ColorObjName}}King Baby{{CR}} obtained",
    [473] = "Gives an additional familiar",
    [474] = "Gives an additional familiar",
    [475] = "", --active
    [476] = "", --active
    [477] = "", --active
    [478] = "", --active
    [479] = "", --active
    [480] = "", --active
    [481] = "", --active
    [482] = "", --active
    [483] = "", --active
    [484] = "", --active
    [485] = "", --active
    [486] = "", --active
    [487] = "", --active
    [488] = "", --active
    [489] = "", --active
    [490] = "", --active
    [491] = "Gives an additional familiar",
    [492] = "Gives an additional familiar, luck up",
    [493] = "No additional effect",
    [494] = "No additional effect",
    [495] = "No additional effect",
    [496] = "No additional effect",
    [497] = "No additional effect",
    [498] = "No additional effect",
    [499] = "No additional effect",
    [500] = "Gives an additional familiar",
    [501] = "No additional effect",
    [502] = "No additional effect",
    [503] = "No additional effect",
    [504] = "", --active
    [505] = "No additional effect",
    [506] = "No additional effect",
    [507] = "", --active
    [508] = "Gives an additional familiar",
    [509] = "Gives an additional familiar",
    [510] = "", --active
    [511] = "Gives an additional familiar",
    [512] = "", --active
    [513] = "Only +1 Soul Heart",
    [514] = "No additional effect",
    [515] = "", --active
    [516] = "", --active
    [517] = "Only +7 bombs",
    [518] = "Gives an additional familiar",
    [519] = "Gives an additional familiar",
    [520] = "No additional effect",
    [521] = "", --active
    [522] = "", --active
    [523] = "", --active
    [524] = "No additional effect",
    [525] = "No additional effect",
    [526] = "Gives an additional familiar",
    [527] = "", --active
    [528] = "Gives an additional familiar",
    [529] = "No additional effect",
    [530] = "No additional effect",
    [531] = "Gives +1 damage",
    [532] = "No additional effect",
    [533] = "No additional effect",
    [534] = "No additional effect",
    [535] = "Only +1 Soul Heart",
    [536] = "", --active
    [537] = "Gives an additional familiar",
    [538] = "Only drops 3 random trinkets",
    [539] = "Gives an additional familiar",
    [540] = "No additional effect",
    [541] = "Additional copies have the same effect",
    [542] = "Additional copies have the same effect",
    [543] = "Gives an additional familiar",
    [544] = "Gives an additional familiar",
    [545] = "", --active
    [546] = "No additional effect",
    [547] = "Additional copies have the same effect",
    [548] = "Gives an additional familiar",
    [549] = "Only replaces heart containers with bone hearts",
    [550] = "", --active
    [551] = "", --QUEST
    [552] = "", --active
    [553] = "No additional effect",
    [554] = "No additional effect",
    [555] = "", --active
    [556] = "", --active
    [557] = "", --active
    [558] = "No additional effect",
    [559] = "No additional effect",
    [560] = "No additional effect",
    [561] = "No additional effect",
    [562] = "No additional effect",
    [563] = "Only +5 bombs",
    [564] = "Additional copies have the same effect",
    [565] = "Gives an additional familiar",
    [566] = "No additional effect",
    [567] = "No extra familiars or additional effect",
    [568] = "No additional effect",
    [569] = "No extra familiars or additional effect",
    [570] = "No additional effect",
    [571] = "Stat changes stack",
    [572] = "Only damage up",
    [573] = "Only HP up",
    [574] = "No additional effect",
    [575] = "No additional effect",
    [576] = "No additional effect",
    [577] = "An extra item is spawned for each copy", --damocles
    [578] = "", --active
    [579] = "No additional effect",
    [580] = "", --active
    [581] = "Gives an additional familiar",
    [582] = "", --active
    [583] = "Only +5 bombs",
    [584] = "", --active
    [585] = "", --active
    [586] = "No additional effect",
    [587] = nil, --NON EXISTANT
    [588] = "No additional effect",
    [589] = "No additional effect",
    [590] = "Only speed up",
    [591] = "Only HP up",
    [592] = "Only damage up",
    [593] = "No additional effect",
    [594] = "Only HP up",
    [595] = "No additional effect",
    [596] = "No additional effect",
    [597] = "No additional effect",
    [598] = "Additional copies have the same effect",
    [599] = "No additional effect",
    [600] = "No additional effect",
    [601] = "Only tears up and +1 Eternal Heart",
    [602] = "No additional effect",
    [603] = "Additional copies have the same effect",
    [604] = "", --active
    [605] = "", --active
    [606] = "No additional effect",
    [607] = "Gives an additional familiar",
    [608] = "Gives an additional familiar",
    [609] = "", --active
    [610] = "Only one {{ColorObjName}}Bird Cage{{CR}} will ever spawn",
    [611] = "", --active
    [612] = "No additional effect, even if previous {{ColorObjName}}Lost Soul{{CR}} died",
    [613] = nil, --NON EXISTANT
    [614] = "Only HP up",
    [615] = "Gives an additional familiar",
    [616] = "No additional effect",
    [617] = "No additional effect",
    [618] = "No additional effect",
    [619] = { -- BIRTHRIGHT
        [PlayerType.PLAYER_MAGDALENE] = "Only HP up",
        [PlayerType.PLAYER_MAGDALENE_B] = "Only HP up",
        [PlayerType.PLAYER_KEEPER] = "Only gain one coin heart",
        [PlayerType.PLAYER_CAIN] = "Only luck up",
        [PlayerType.PLAYER_APOLLYON] = "No additional effect",
        [PlayerType.PLAYER_APOLLYON_B] = "No additional effect",
        [PlayerType.PLAYER_AZAZEL] = "No additional effect",
        [PlayerType.PLAYER_AZAZEL_B] = "No additional effect",
        [PlayerType.PLAYER_BETHANY] = "No additional effect",
        [PlayerType.PLAYER_BETHANY_B] = "No additional effect",
        [PlayerType.PLAYER_BLACKJUDAS] = "No additional effect",
        [PlayerType.PLAYER_BLUEBABY] = "No additional effect",
        [PlayerType.PLAYER_BLUEBABY_B] = "No additional effect",
        [PlayerType.PLAYER_CAIN_B] = "No additional effect",
        [PlayerType.PLAYER_EDEN] = "No additional effect",
        [PlayerType.PLAYER_EDEN_B] = "No additional effect",
        [PlayerType.PLAYER_ESAU] = "No additional effect",
        [PlayerType.PLAYER_EVE] = "No additional effect",
        [PlayerType.PLAYER_EVE_B] = "No additional effect",
        [PlayerType.PLAYER_ISAAC] = "No additional effect",
        [PlayerType.PLAYER_ISAAC_B] = "No additional effect",
        [PlayerType.PLAYER_JACOB] = "No additional effect",
        [PlayerType.PLAYER_JACOB2_B] = "No additional effect",
        [PlayerType.PLAYER_JACOB_B] = "No additional effect",
        [PlayerType.PLAYER_JUDAS] = "No additional effect",
        [PlayerType.PLAYER_JUDAS_B] = "No additional effect",
        [PlayerType.PLAYER_KEEPER_B] = "No additional effect",
        [PlayerType.PLAYER_LAZARUS] = "No additional effect",
        [PlayerType.PLAYER_LAZARUS2] = "No additional effect",
        [PlayerType.PLAYER_LAZARUS2_B] = "No additional effect",
        [PlayerType.PLAYER_LAZARUS_B] = "No additional effect",
        [PlayerType.PLAYER_LILITH] = "No additional effect",
        [PlayerType.PLAYER_LILITH_B] = "No additional effect",
        [PlayerType.PLAYER_POSSESSOR] = "No additional effect",
        [PlayerType.PLAYER_SAMSON] = "No additional effect",
        [PlayerType.PLAYER_SAMSON_B] = "No additional effect",
        [PlayerType.PLAYER_THEFORGOTTEN] = "No additional effect",
        [PlayerType.PLAYER_THEFORGOTTEN_B] = "No additional effect",
        [PlayerType.PLAYER_THELOST] = "No additional effect",
        [PlayerType.PLAYER_THELOST_B] = "No additional effect",
        [PlayerType.PLAYER_THESOUL] = "No additional effect",
        [PlayerType.PLAYER_THESOUL_B] = "No additional effect"
    },
    [620] = nil, --NON EXISTANT
    [621] = "Resets bonus to full amount",
    [622] = "", --active
    [623] = "", --active
    [624] = "Additional copies have the same effect",
    [625] = "", --active
    [626] = "Gives an additional familiar",
    [627] = "Gives an additional familiar",
    [628] = "", --active
    [629] = "Gives an additional familiar",
    [630] = nil, --NON EXISTANT
    [631] = "", --active
    [632] = "Only luck up",
    [633] = "Only damage up, heal, and mantle effect for the room",
    [634] = "No additional effect",
    [635] = "", --active
    [636] = "", --active
    [637] = "No additional effect",
    [638] = "", --active
    [639] = "", --active
    [640] = "", --active
    [641] = "No additional effect",
    [642] = "", --active
    [643] = "Only +2 Soul Hearts",
    [644] = "Stat changes stack",
    [645] = "Gives an additional familiar",
    [646] = "Only +5 bombs",
    [647] = "No additional effect",
    [648] = nil, --NON EXISTANT
    [649] = "Gives an additional familiar",
    [650] = "", --active
    [651] = "No extra familiars or additional effect",
    [652] = "Gives an additional familiar",
    [653] = "", --active
    [654] = "Only +1 Black Heart",
    [655] = "", --active
    [656] = "An extra item is spawned for each copy", --Damocles passive
    [657] = "No additional effect",
    [658] = "No additional effect",
    [659] = "Only range up",
    [660] = "No additional effect",
    [661] = "Can create 5 extra familiars per copy",
    [662] = nil, --NON EXISTANT
    [663] = "No additional effect",
    [664] = "Only HP up",
    [665] = "No additional effect",
    [666] = nil, --NON EXISTANT
    [667] = "Can spawn multiple Keepers",
    [668] = "", --QUEST
    [669] = "Stat changes stack, does not increase deal/Planetarium chance further",
    [670] = "No additional effect",
    [671] = "No additional effect",
    [672] = "No additional effect",
    [673] = "No additional effect",
    [674] = "No additional effect",
    [675] = "No additional effect",
    [676] = "No additional effect",
    [677] = "No additional effect",
    [678] = "No additional effect",
    [679] = "Gives an additional familiar",
    [680] = "No additional effect",
    [681] = "Gives an additional familiar",
    [682] = "Gives an additional familiar",
    [683] = "No additional effect",
    [684] = "No additional effect",
    [685] = "", --active
    [686] = "No additional effect",
    [687] = "", --active
    [688] = "Gives another respawn with the same effect",
    [689] = "No additional effect",
    [690] = "No additional effect",
    [691] = "No additional effect",
    [692] = "No additional effect",
    [693] = "Only gives another 8 orbital flies",
    [694] = "Grants 3 more broken hearts along with damage from them",
    [695] = "No additional effect",
    [696] = "No additional effect",
    [697] = "Multiple clones will be spawned in boss rooms, each spawning an item#Each clone will have 75% of the health of the previous clone",
    [698] = "Gives an additional familiar, positioned beside the others",
    [699] = "No additional effect",
    [700] = "No additional effect",
    [701] = "Only one chest is spawned per floor",
    [702] = "No additional effect",
    [703] = "", --active
    [704] = "", --active
    [705] = "", --active
    [706] = "", --active
    [707] = "Additional copies have the same effect",
    [708] = "Additional copies have the same effect",
    [709] = "", --active
    [710] = "", --active
    [711] = "", --active
    [712] = "", --active
    [713] = "", --active
    [714] = "", --active
    [715] = "", --active
    [716] = "Only drops pickups",
    [717] = "No additional effect",
    [718] = nil, --NON EXISTANT
    [719] = "", --active
    [720] = "", --active
    [721] = "No additional effect",
    [722] = "", --active
    [723] = "", --active
    [724] = "No additional effect",
    [725] = "No additional effect",
    [726] = "No additional effect",
    [727] = "Only +5 bombs",
    [728] = "", --active
    [729] = "", --active
    [730] = "Additional copies have the same effect",
    [731] = "No additional effect",
    [732] = "Additional copies have the same effect",
}